import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { StyledRoot } from './StyledRoot';


import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import AppKitProvider from "@/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body >
      <AppRouterCacheProvider>
      {/* <StyledRoot>{children}</StyledRoot> */}
        <AppKitProvider initialState={initialState}>{children}</AppKitProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
